# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chatnovel' do
  platform :ios, '10.0'

  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
  ]
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Database'
  pod 'Firebase/RemoteConfig'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
end
