# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chatnovel' do
  # use_frameworks!
  platform :ios, '9.0'

  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
  ]
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Database'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Crash'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod 'Fabric'
  pod 'Crashlytics'
  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

  pod 'react-native-in-app-utils', :path => '../node_modules/react-native-in-app-utils'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RNShare', :path => '../node_modules/react-native-share'
  pod 'react-native-blur', :path => '../node_modules/react-native-blur'
end
