# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.51.0"

default_platform :ios

platform :ios do
  before_all do
    sh("cd ../../ && yarn run schemes-manager")
    cocoapods(repo_update: true)
    sh("" +
      "cd ../../node_modules/react-native && " +
      "(./scripts/ios-install-third-party.sh || ./scripts/ios-install-third-party.sh) && " +
      "cd third-party/glog-0.3.4 && " +
      "../../scripts/ios-configure-glog.sh"
    )
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number

    info_plist_pah = "chatnovel/Info.plist"
    update_info_plist(
      plist_path: info_plist_pah,
      display_name: "[dev] CHAT NOVEL",
    )
    update_url_schemes(
      path: info_plist_pah,
      url_schemes: ["dev-chatnovel"],
    )

    gym(scheme: "dev chatnovel")
    pilot(skip_waiting_for_build_processing: true)

    reset_git_repo(force: true)
    ensure_git_status_clean
    increment_build_number
    commit_version_bump(
      message: 'build version bump [ci skip]',
      xcodeproj: 'chatnovel.xcodeproj',
    )
    push_to_git_remote(
      remote: "origin",
      local_branch: "HEAD",
      remote_branch: "master",
      tags: true,
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :release do
    increment_build_number

    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "chatnovel")
    pilot(skip_waiting_for_build_processing: true)

    reset_git_repo(force: true)
    ensure_git_status_clean
    increment_build_number
    commit_version_bump(
      message: 'build version bump [ci skip]',
      xcodeproj: 'chatnovel.xcodeproj',
    )
    push_to_git_remote(
      remote: "origin",
      local_branch: "HEAD",
      remote_branch: "release",
      tags: true,
    )
  end
end
